apiVersion: v2
name: qs-redis-standalone
version: 0.16.7
appVersion: "0.16.7"
description: Pharia AI Quick Start Helm chart for Redis
home: https://github.com/ot-container-kit/redis-operator
icon: https://aleph-alpha.com/wp-content/themes/sbd-blank/dist/img/logo.svg

dependencies:
  - name: redis
    version: 0.16.7
    repository: https://ot-container-kit.github.io/helm-charts/

