apiVersion: v2
name: qs-postgresql-operator
home: https://aleph-alpha.com/phariaai/
icon: https://aleph-alpha.com/wp-content/themes/sbd-blank/dist/img/logo.svg
description: Pharia AI Quick Start Helm chart for Cloudnative PG Operator
version: 0.1.2

dependencies:
  - name: cloudnative-pg
    version: 0.26.1
    repository: https://cloudnative-pg.github.io/charts
