cloudnative-pg:
  crds:
    # -- Specifies whether the CRDs should be created when installing the chart.
    create: true
  rbac:
    # -- Specifies whether ClusterRole and ClusterRoleBinding should be created.
    create: true
    # -- Aggregate ClusterRoles to Kubernetes default user-facing roles.
    # Ref: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles
    aggregateClusterRoles: false
  # -- Annotations to be added to all other resources.
  commonAnnotations: {}
  # -- Annotations to be added to the pod.
  podAnnotations: {}
  # -- Container Security Context
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsUser: 10001
    runAsGroup: 10001
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - "ALL"
  # -- Security Context for the whole pod.
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
    # fsGroup: 2000
  # Operator configuration.
  config:
    # -- This option determines if the operator is responsible for observing
    # events across the entire Kubernetes cluster or if its focus should be
    # narrowed down to the specific namespace within which it has been deployed.
    clusterWide: false
    # -- The content of the configmap/secret, see
    # https://cloudnative-pg.io/documentation/current/operator_conf/#available-options
    # for all the available options.
    data: {}
    # INHERITED_ANNOTATIONS: maintainer
    # INHERITED_LABELS: environment, workload, app
    # WATCH_NAMESPACE: namespace-a,namespace-b
