apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "qs-pgbouncer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qs-pgbouncer.labels" . | nindent 4 }}
    app.kubernetes.io/component: service-account
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
automountServiceAccountToken: true
