{{- if and .Values.secretGenerationJob.enabled .Values.clusterTemporal.enabled }}
{{- include "qs-postgresql-cluster.secretCreationJob" (dict "root" . "clusterName" "temporal" "clusterConfig" .Values.clusterTemporal) }}
{{- end }}
