{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "qs-postgresql-cluster.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qs-postgresql-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: service-account
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-delete
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: true
{{- end }}
