apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pharia-ai

resources:
  - configmap-script.yaml
  - configmap-config.yaml
  - job.yaml

commonLabels:
  app: db-migration
  managed-by: kustomize
