{{- if (index .Values "redis-operator" "rbac" "create") -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ index .Values "redis-operator" "rbac" "serviceAccountName" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "qs-redis-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "qs-redis-operator.chart" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ index .Values "redis-operator" "rbac" "serviceAccountName" }}
subjects:
  - kind: ServiceAccount
    name: {{ index .Values "redis-operator" "rbac" "serviceAccountName" }}
    namespace: {{ .Release.Namespace }}
{{- end }}

