{{- if .Values.customRbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.customRbac.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "qs-redis-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "qs-redis-operator.chart" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.customRbac.serviceAccountName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.customRbac.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
{{- end }}
