apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "qs-redis-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "qs-redis-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "qs-redis-operator.chart" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "qs-redis-operator.roleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "qs-redis-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
