{{- if (index .Values "redis-operator" "rbac" "create") -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ index .Values "redis-operator" "rbac" "serviceAccountName" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "qs-redis-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "qs-redis-operator.chart" . }}
{{- end }}

