{{- if .Values.secretGenerationJob.enabled }}
{{- range $key, $value := .Values }}
{{- if and (hasPrefix "minio-" $key) (kindIs "map" $value) }}
{{- if $value.enabled }}
{{- $instanceName := trimPrefix "minio-" $key }}
---
{{- include "qs-minio.secretCreationJob" (dict "root" $ "instanceName" $instanceName "instanceConfig" $value) }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}

