apiVersion: v1
kind: Secret
metadata:
  name: qdrant-credentials
  namespace: pharia-ai
type: Opaque
stringData:
  QDRANT_S3_ACCESS_KEY_ID: your-s3-access-key-id
  QDRANT_S3_SECRET_ACCESS_KEY: your-s3-secret-access-key
  QDRANT_S3_BUCKET_NAME: your-s3-bucket-name
  QDRANT_API_KEY: your-api-key
