apiVersion: v2
name: qs-redis-operator
description: Quick Start Helm chart for Redis Operator
version: 3.3.0
appVersion: 1.3.0
home: https://github.com/spotahome/redis-operator
icon: https://aleph-alpha.com/wp-content/themes/sbd-blank/dist/img/logo.svg
keywords:
  - "operator"
  - "cluster"
sources:
  - https://github.com/spotahome/redis-operator
kubeVersion: ">=1.21.0-0"
