apiVersion: v2
name: qs-postgresql-db
home: https://aleph-alpha.com/phariaai/
icon: https://aleph-alpha.com/wp-content/themes/sbd-blank/dist/img/logo.svg
description: Helm chart for declaratively managing CloudNativePG PostgreSQL databases with full CRD specification support
version: 0.1.1
keywords:
  - postgresql
  - cloudnative-pg
  - cnpg
  - database
  - operator
maintainers:
  - name: Pharia AI Platform Team
sources:
  - https://cloudnative-pg.io/
annotations:
  category: Database
  licenses: Apache-2.0
