stakater/reloader
apteno/alpine-jq
bitnami/kubectl
bitnami/mlflow
curlimages/curl
openfga/openfga
qdrant/qdrant
rayproject/ray
zitadel/zitadel
kuberay/operator
dexidp/dex
kserve/kserve-controller
brancz/kube-rbac-proxy
prometheuscommunity/postgres-exporter
pharia-application-registry/pottery
temporalio/admin-tools
temporalio/server
temporalio/ui
cloudnative-pg/postgresql
cloudnative-pg/cloudnative-pg
bitnamilegacy/mlflow
inference-images/model-downloader
document-index-mcp/document-index-mcp
container-images/finetuning_api
pharia-numinous-images/pharia-numinous
pharia-numinous-images/mcp-code-sandbox
assistant-applications/generate-template
assistant-applications/summary-template
pharia-os-images/pharia-os-manager
pharia-os-images/phariaos-applications-proxy