apiVersion: v2
name: qs-minio-operator
home: https://aleph-alpha.com/phariaai/
icon: https://aleph-alpha.com/wp-content/themes/sbd-blank/dist/img/logo.svg
description: Pharia AI Quick Start Helm chart for Minio Operator
version: 0.1.0

dependencies:
  - name: operator
    version: 7.1.1
    repository: https://operator.min.io
